/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.awt.Frame;
import javax.swing.JOptionPane;
import static modelo.ConexionBD.conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelo.InventarioAmbiente;
import modelo.Ambiente;

/**
 *
 * @author lemag
 */
public class FRMDetalleInventario extends javax.swing.JInternalFrame {

    private javax.swing.JDesktopPane escritorio;
    private int idAmbiente;

    /**
     * Creates new form FRMDetalleInventario
     */
    public FRMDetalleInventario() {
        initComponents();
        addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent e) {
                javax.swing.JDesktopPane dp = escritorio;
                if (dp == null) return;
                for (javax.swing.JInternalFrame f : dp.getAllFrames()) {
                    if (f instanceof FRMLogin) return;
                }
                for (javax.swing.JInternalFrame f : dp.getAllFrames()) {
                    if (f instanceof FRMInventario) {
                        f.setVisible(true);
                        return;
                    }
                }
            }
        });
    }

    @Override
    public void addNotify() {
        super.addNotify();
        escritorio = getDesktopPane();
    }
    
    public void cargarInformacionInventario(int idAmbiente) {
        this.idAmbiente = idAmbiente;

    try {
        PreparedStatement ps = conexion.prepareStatement(
            "SELECT nombre, tipo, ubicacion FROM ambiente WHERE id = ?");

        ps.setInt(1, idAmbiente);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            lb_titulo.setText(rs.getString("nombre"));
            txt_informacion.setText(
                "Tipo: " + rs.getString("tipo") +
                " | Ubicación: " + rs.getString("ubicacion")
            );
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    cargarItemsInventario(idAmbiente);
}

    public void cargarItemsInventario(int idAmbiente) {
        DefaultTableModel modelo = (DefaultTableModel) tb_itemInventario.getModel();
        modelo.setRowCount(0);

        InventarioAmbiente ia = new InventarioAmbiente();
        java.util.Iterator<InventarioAmbiente> lista = ia.listarPorAmbiente(idAmbiente);

        while (lista.hasNext()) {
            InventarioAmbiente item = lista.next();
            String estado = item.tieneStockBajo() ? "Stock bajo" : "Normal";
            modelo.addRow(new Object[]{
                item.getNombreArticulo(),
                item.getCantidad(),
                item.getCantidadMinima(),
                estado,
                ""
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_Cerrar_sesion = new javax.swing.JButton();
        bt_volver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        bt_checklist = new javax.swing.JButton();
        bt_NuevaSolicitud = new javax.swing.JButton();
        bt_NuevoReporte = new javax.swing.JButton();
        bt_editar_Inventario = new javax.swing.JButton();
        bt_historial_Inventario = new javax.swing.JButton();
        txt_informacion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_itemInventario = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Gestion de Inventarios ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario: admin ");

        bt_Cerrar_sesion.setText("Cerrar sesión");
        bt_Cerrar_sesion.addActionListener(this::bt_Cerrar_sesionActionPerformed);

        bt_volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_volver.addActionListener(this::bt_volverActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_Cerrar_sesion)
                                .addGap(356, 356, 356))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(bt_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_Cerrar_sesion)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lb_titulo.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        bt_checklist.setText("Iniciar Checklist");

        bt_NuevaSolicitud.setText("Nueva Solicitud");
        bt_NuevaSolicitud.addActionListener(this::bt_NuevaSolicitudActionPerformed);

        bt_NuevoReporte.setText("Nuevo Reporte");
        bt_NuevoReporte.addActionListener(this::bt_NuevoReporteActionPerformed);

        bt_editar_Inventario.setText("Editar Inventario ");
        bt_editar_Inventario.addActionListener(this::bt_editar_InventarioActionPerformed);

        bt_historial_Inventario.setText("Histrorial de inventario");
        bt_historial_Inventario.addActionListener(this::bt_historial_InventarioActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_checklist, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_NuevaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_NuevoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editar_Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_historial_Inventario)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_checklist)
                    .addComponent(bt_NuevaSolicitud)
                    .addComponent(bt_NuevoReporte)
                    .addComponent(bt_editar_Inventario)
                    .addComponent(bt_historial_Inventario))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Items del Inventario");

        tb_itemInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Artículo", "Cantidad Actual ", "Cantidad Minima", "Estado", "Acciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_itemInventario);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Cerrar_sesionActionPerformed
       int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Desea cerrar sesión?",
            "Cerrar sesión",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            FRMLogin login = new FRMLogin();
            this.getDesktopPane().add(login);
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_bt_Cerrar_sesionActionPerformed

    private void bt_historial_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_historial_InventarioActionPerformed
        FRMHistorialRevisiones historial = new FRMHistorialRevisiones();

        this.getDesktopPane().add(historial);
        historial.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_bt_historial_InventarioActionPerformed

    private void bt_NuevaSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_NuevaSolicitudActionPerformed
       Frame padre = (Frame) SwingUtilities.getWindowAncestor(this);

       DGSolicitud dialog = new DGSolicitud(padre, true);
       dialog.setLocationRelativeTo(padre);
       dialog.setVisible(true);
    }//GEN-LAST:event_bt_NuevaSolicitudActionPerformed

    private void bt_NuevoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_NuevoReporteActionPerformed
        Frame padre = (Frame) SwingUtilities.getWindowAncestor(this);

       DGReporte dialog = new DGReporte(padre, true);
       dialog.setLocationRelativeTo(padre);
       dialog.setVisible(true);
    }//GEN-LAST:event_bt_NuevoReporteActionPerformed

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        javax.swing.JDesktopPane dp = getDesktopPane();
        if (dp == null) return;
        for (javax.swing.JInternalFrame f : dp.getAllFrames()) {
            if (f instanceof FRMInventario) {
                f.setVisible(true);
                break;
            }
        }
        this.dispose();
    }//GEN-LAST:event_bt_volverActionPerformed

    private void bt_editar_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editar_InventarioActionPerformed
        Ambiente amb = new Ambiente().buscarPorId(idAmbiente);
        if (amb == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el ambiente");
            return;
        }
        javax.swing.JDesktopPane dp = getDesktopPane();
        if (dp == null) return;
        for (javax.swing.JInternalFrame f : dp.getAllFrames()) {
            if (f instanceof FRMInventario) {
                FRMNEditarInventario nuevoAmb = new FRMEditarInventario((FRMInventario) f);
                nuevoAmb.cargarAmbiente(amb);
                dp.add(nuevoAmb);
                nuevoAmb.setVisible(true);
                setVisible(false);
                break;
            }
        }
    }//GEN-LAST:event_bt_editar_InventarioActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cerrar_sesion;
    private javax.swing.JButton bt_NuevaSolicitud;
    private javax.swing.JButton bt_NuevoReporte;
    private javax.swing.JButton bt_checklist;
    private javax.swing.JButton bt_editar_Inventario;
    private javax.swing.JButton bt_historial_Inventario;
    private javax.swing.JButton bt_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTable tb_itemInventario;
    private javax.swing.JTextField txt_informacion;
    // End of variables declaration//GEN-END:variables
}
