
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

db.driver =org.postgresql.Driver
db.url =jdbc:postgresql://144.91.74.225:5438/inventarios_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Bogota
db.user =juan
db.clave =postgres1234

